export const placesArray = [
  "Acorn_Hall",
  "Aegonfort",
  "Andalos",
  "Antler_River",
  "Antlers",
  "The_Arbor",
  "Arsenal_of_Braavos",
  "Ashemark",
  "Ashford",
  "Asshai",
  "The_Axe",
  "Bandallon",
  "The_Banefort",
  "Barrowlands",
  "Barrowton",
  "Barter_Beach",
  "Basilisk_Isles",
  "Bay_of_Ice",
  "Bay_of_Seals",
  "Bear_Island",
  "Beyond_the_Wall",
  "Bhorash",
  "The_Bite",
  "Bitterbridge",
  "Black_Cells",
  "Black_Cliffs",
  "Black_Wall",
  "Blackhaven",
  "Blackmont",
  "Blacktyde",
  "Blackwater_Bay",
  "Blackwater_Rush",
  "Blazewater_Bay",
  "Bloody_Gate",
  "Bone_Mountains",
  "Boneway",
  "Braavos",
  "Braavosian_Coastlands",
  "Brightwater_Keep",
  "Brimstone",
  "Broken_Branch",
  "Bronzegate",
  "Cape_Kraken",
  "Cape_of_Eagles",
  "Castamere",
  "Casterly_Rock",
  "Castle_Black",
  "Castle_Cerwyn",
  "Castle_Stokeworth",
  "Cave_of_the_Three-Eyed_Raven",
  "Chamber_of_the_Painted_Table",
  "Cider_Hall",
  "The_Citadel",
  "Claw_Isle",
  "Clegane_s_Keep",
  "Cornfield",
  "Crackclaw_Point",
  "The_Crag",
  "Crakehall",
  "Craster_s_Keep",
  "Crow_s_Nest",
  "The_Crownlands",
  "Deep_Den",
  "Deep_Lake",
  "Deepwood_Motte",
  "Disputed_Lands",
  "Dorne",
  "Dornish_Marches",
  "Dothraki_Sea",
  "Dragonpit",
  "Dragonstone_island",
  "Driftmark",
  "Duskendale",
  "Eastwatch-by-the-Sea",
  "Evenfall_Hall",
  "The_Eyrie                   ",
  "Fair_Isle",
  "Faircastle",
  "Fairmarket",
  "Feastfires",
  "Felwood",
  "The_Fingers",
  "Fist_of_the_First_Men",
  "Flatlands",
  "Flea_Bottom",
  "Flint_s_Finger",
  "Forest_of_Qohor",
  "Free_Cities",
  "Frostfangs",
  "Frozen_Shore",
  "Garden_of_Bones_Qarth",
  "Ghiscari_Strait",
  "Ghost_Hill",
  "The_Gift",
  "Gods_Eye",
  "Godsgrace",
  "Godsway",
  "Golden_Fields",
  "Golden_Tooth",
  "Goldengrove",
  "Grassy_Vale",
  "Great_Hall",
  "Great_Pyramid",
  "Great_Sept_of_Baelor",
  "Great_Wyk",
  "Greenblood",
  "The_Grey_Cliffs",
  "Greyguard",
  "Greywater_Watch",
  "Griffin_s_Roost",
  "Guildhall_of_the_Alchemists",
  "Gullet",
  "Gulltown",
  "Hall_of_a_Thousand_Thrones",
  "Hall_of_Faces",
  "Hammerhorn",
  "Hardstone_Hills",
  "Harlaw",
  "Haunted_Forest",
  "Haystack_Hall",
  "Hellholt",
  "High_Heart",
  "Highgarden",
  "The_Hightower",
  "Hills_of_Norvos",
  "Hollow_Hill",
  "Honeyholt",
  "Honeywine",
  "Horn_Hill",
  "Hornvale",
  "Hornwood",
  "Horse_Gate",
  "House_of_Black_and_White",
  "House_of_the_Undying",
  "Ib",
  "Inn_at_the_Crossroads",
  "Iron_Islands",
  "Ironman_s_Bay",
  "Isle_of_Faces",
  "Isle_of_Tears",
  "Isle_of_the_Gods",
  "Karhold",
  "King_s_Gate",
  "King_s_Landing",
  "Kingsgrave",
  "Kingsroad",
  "Kingswood",
  "Lands_of_Always_Winter",
  "Lannisport",
  "Last_Hearth",
  "Last_River",
  "Lemonwood",
  "Lhazar",
  "Lonely_Hills",
  "Long_Barrow",
  "Long_Bridge",
  "Long_Lake",
  "Long_Table",
  "Lorath",
  "Lord_Harroway_s_Town",
  "Lordsport",
  "Lys",
  "Maegor_s_Holdfast",
  "Maidenpool",
  "Maidenvault",
  "Milkwater",
  "Mistwood",
  "Moat_Cailin",
  "Mole_s_Town",
  "Moon_Pool",
  "Moonsinger_Lane",
  "Mother_of_Mountains",
  "Mountains_of_the_Moon",
  "Mud_Gate",
  "Muddy_Way",
  "Myr",
  "Naath",
  "The_Neck",
  "New_Ghis",
  "The_Nightfort",
  "Nightsong",
  "North_Grove",
  "The_North",
  "Norvos",
  "Old_Ghis",
  "Old_Oak",
  "Old_Valyria",
  "Old Wyk",
  "Oldcastle",
  "Oldtown",
  "Orange Shore",
  "Orkmont",
  "Oros",
  "Osric_s Hill",
  "Palace of Justice",
  "Pentos",
  "Pinkmaiden",
  "Port of Ibben",
  "Prince_s Pass",
  "Pyke (castle)",
  "Pyke (island)",
  "Qarth",
  "Qohor",
  "Queenscrown",
  "Rain House",
  "Rainwood",
  "Ramsgate",
  "Raventree Hall",
  "The Reach",
  "Red Keep",
  "Red Lake",
  "Red Waste",
  "The Redfort",
  "Redwyne Straits",
  "Rhoyne",
  "The Rills",
  "The Riverlands",
  "Riverrun",
  "Rook_s Rest",
  "Rosby",
  "Roseroad",
  "Ruby Ford",
  "Saltcliffe",
  "Saltpans",
  "Saltshore",
  "Samyrian",
  "Sandstone",
  "Sarsfield",
  "Scourge",
  "Sea Dragon Point",
  "Sea of Myrth",
  "Seagard",
  "Sealord_s Palace",
  "Searoad",
  "Selhorys",
  "Sept",
  "Sept of Remembrance",
  "The Shadow Tower",
  "Sheelba Square",
  "Shield Islands",
  "Shipbreaker Bay",
  "Silverhill",
  "Skagos",
  "Skane",
  "Skirling Pass",
  "Skull Island",
  "Skyreach",
  "Slaver_s Bay",
  "Smoking Sea",
  "Starfall",
  "Starry Sept",
  "Stepstones",
  "Stone Hedge",
  "Stonehelm",
  "Stoney Sept",
  "Stony Shore",
  "Storm_s End",
  "The Stormlands",
  "Summer Islands",
  "Summerhall",
  "Sunflower Hall",
  "Sunspear",
  "Sweetwater River",
  "Tarbeck Hall",
  "Tarth",
  "Temple of the Dosh khaleen",
  "Temple of the Lord of Light (Braavos)",
  "Temple of the Lord of Light (Volantis)",
  "Temple of the Moonsingers",
  "Ten Towers",
  "Three Sisters",
  "Three Towers",
  "Titan of Braavos",
  "The Tor",
  "Torrhen_s Square",
  "Tower of Joy",
  "Tower of the Hand",
  "The Trident",
  "Tumbleton",
  "The Twins",
  "Tyria",
  "Tyrosh",
  "Unnamed Baelish castle",
  "Uplands",
  "Vaes Dothrak",
  "Vaith",
  "Vaith (river)",
  "The Vale of Arryn",
  "Valyrian Peninsula",
  "Valysar",
  "Volantis",
  "Volon Therys",
  "Vulture_s Roost",
  "Walk of Punishment (Astapor)",
  "The Wall",
  "Water Gardens",
  "Weeping Water",
  "Wendish Town",
  "The Westerlands",
  "Whispering Wood",
  "The Whispers",
  "White Harbor",
  "White Knife",
  "White Sword Tower",
  "White Tree",
  "Wickendon",
  "Widow_s Watch",
  "Winter town",
  "Wolfswood",
  "Wyl (castle)",
  "Yaros",
  "Yi Ti",
  "Yronwood"
];
